# Generated by Django 4.2.7 on 2025-09-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hatırlatma Zamanı'),
        ),
    ]
