# Generated by Django 4.2.7 on 2025-12-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_reminder_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
